/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.44
 * Generated at: 2017-08-10 19:19:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class account_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/career/bell%20Info/final%20project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/flights-car-reservation/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153399482000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.10.RELEASE.jar", Long.valueOf(1500682600166L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1500682496543L));
    _jspx_dependants.put("jar:file:/D:/career/bell%20Info/final%20project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/flights-car-reservation/WEB-INF/lib/spring-webmvc-4.3.10.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1500565206000L));
    _jspx_dependants.put("jar:file:/D:/career/bell%20Info/final%20project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/flights-car-reservation/WEB-INF/lib/spring-webmvc-4.3.10.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1500565206000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("\r\n");
      out.write("background:white;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".thumbnail\r\n");
      out.write("{\r\n");
      out.write("    margin-bottom: 40px;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("    -webkit-border-radius: 0px;\r\n");
      out.write("    -moz-border-radius: 0px;\r\n");
      out.write("    border-radius: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item.list-group-item\r\n");
      out.write("{\r\n");
      out.write("    float: none;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write(".item.list-group-item:nth-of-type(odd):hover,.item.list-group-item:hover\r\n");
      out.write("{\r\n");
      out.write("    background: #428bca;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item.list-group-item .list-group-image\r\n");
      out.write("{\r\n");
      out.write("    margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".item img{\r\n");
      out.write("\t\r\n");
      out.write("\tdisplay:inline-block; \t\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item\r\n");
      out.write("{\r\n");
      out.write("text-align:center;\r\n");
      out.write("display: inline-block;     /* arranging the div elements-->*/\r\n");
      out.write("  margin: 0px 2% 5rem 2%;\r\n");
      out.write("  width: 45%;\r\n");
      out.write("  position:relative;\r\n");
      out.write("  overflow:hidden;  /* setting responsive design */\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <a class=\"navbar-brand\">Reservations</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("       <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/contact\"><span class=\"glyphicon glyphicon-earphone\"></span> Contact</a></li>\r\n");
      out.write("   <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\"><span class=\"glyphicon glyphicon-log-out\"></span> Log-out</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <br><br>\r\n");
      out.write("    <div id=\"products\" class=\"row list-group\">\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <div class=\"thumbnail\">\r\n");
      out.write("                <img src=\"http://www.arppartners.com/eng/images/ethiad.jpg\" />\r\n");
      out.write("                <div class=\"caption\">\r\n");
      out.write("                    <h4 class=\"group inner list-group-item-heading\">\r\n");
      out.write("                        Explore USA</h4>\r\n");
      out.write("                    <p class=\"group inner list-group-item-text\">\r\n");
      out.write("                        We help you find the most economical airline tickets</p>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <form class=\"form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/search\" method=\"get\">\r\n");
      out.write("  \r\n");
      out.write("    <label for=\"name\"></label>\r\n");
      out.write("    \r\n");
      out.write(" <div class=\"wrap\">\r\n");
      out.write("                             <button type=\"submit\" class=\"btn btn-success btn-lg\">Search Flights</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <div class=\"thumbnail\">\r\n");
      out.write("                <img src=\"http://www.hdcarwallpapers.com/walls/bmw_4_series_gran_coupe_m3-HD.jpg\"/>\r\n");
      out.write("                <div class=\"caption\">\r\n");
      out.write("                    <h4 class=\"group inner list-group-item-heading\">\r\n");
      out.write("                        Search Cars</h4>\r\n");
      out.write("                    <p class=\"group inner list-group-item-text\">\r\n");
      out.write("                     Find cars with the cheapest prices around </p>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write(" <form class=\"form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cars\" method=\"get\">\r\n");
      out.write("  \r\n");
      out.write("    <label for=\"name\"></label>\r\n");
      out.write("    <br>\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("  <button type=\"submit\" class=\"btn btn-success btn-lg\"> Search Cars</button>\r\n");
      out.write("  </div>\r\n");
      out.write("  </form>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <div class=\"thumbnail\">\r\n");
      out.write("                <img src=\"https://fthmb.tqn.com/oq7X6EFyCgjY-47vgZSIBUTZYlw=/768x0/filters:no_upscale()/about/bills-57d1a3d83df78c71b633a31d.png\"/>\r\n");
      out.write("                <div class=\"caption\">\r\n");
      out.write("                    <h4 class=\"group inner list-group-item-heading\">\r\n");
      out.write("                        Car Bills</h4>\r\n");
      out.write("                        <p class=\"group inner list-group-item-text\">\r\n");
      out.write("                        View the Previous Billings of Your Cars\r\n");
      out.write("                      </p>\r\n");
      out.write("                      <br>\r\n");
      out.write("                         <form class=\"form-horizontal\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/carbills\" method=\"get\">\r\n");
      out.write("    \r\n");
      out.write("  <button type=\"submit\" class=\"btn btn-success btn-lg\">Car Bills</button>\r\n");
      out.write("  \r\n");
      out.write("  </form>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"item\">\r\n");
      out.write("            <div class=\"thumbnail\">\r\n");
      out.write("                <img src=\"https://fthmb.tqn.com/oq7X6EFyCgjY-47vgZSIBUTZYlw=/768x0/filters:no_upscale()/about/bills-57d1a3d83df78c71b633a31d.png\"/>\r\n");
      out.write("                <div class=\"caption\">\r\n");
      out.write("                    <h4 class=\"group inner list-group-item-heading\">\r\n");
      out.write("                        Flight Bills</h4>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <p class=\"group inner list-group-item-text\">\r\n");
      out.write("                    View Previous Billings of Flight Tickets\r\n");
      out.write("                     </p>\r\n");
      out.write("                     <br>\r\n");
      out.write("\r\n");
      out.write("                        <form class=\"form-horizontal\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/flightbills\" method=\"get\">\r\n");
      out.write("    \r\n");
      out.write("  <button type=\"submit\" class=\"btn btn-success btn-lg\">Flight Bills</button>\r\n");
      out.write("  \r\n");
      out.write("  </form>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
