/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.44
 * Generated at: 2017-08-10 20:13:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("                      \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" \r\n");
      out.write("integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" \r\n");
      out.write("crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Oleo+Script:400,700\" rel=\"stylesheet\">\r\n");
      out.write("   \t<link href=\"https://fonts.googleapis.com/css?family=Teko:400,700\" rel=\"stylesheet\">\r\n");
      out.write("   \t<link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  \r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("/*Contact sectiom*/\r\n");
      out.write(".content-header{\r\n");
      out.write("  font-family: 'Oleo Script', cursive;\r\n");
      out.write("  color:#fcc500;\r\n");
      out.write("  font-size: 45px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".section-content{\r\n");
      out.write("  text-align: center; \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("#contact{\r\n");
      out.write("    \r\n");
      out.write("    font-family: 'Teko', sans-serif;\r\n");
      out.write("  padding-top: 60px;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  width: 100vw;\r\n");
      out.write("  \r\n");
      out.write("  height: 550px;\r\n");
      out.write("  background: #3a6186; /* fallback for old browsers */\r\n");
      out.write("  background: -webkit-linear-gradient(to left, #3a6186 , #89253e); /* Chrome 10-25, Safari 5.1-6 */\r\n");
      out.write("  background: linear-gradient(to left, #3a6186 , #89253e); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */\r\n");
      out.write("    color : #fff;    \r\n");
      out.write("}\r\n");
      out.write(".contact-section{\r\n");
      out.write("  padding-top: 40px;\r\n");
      out.write("}\r\n");
      out.write(".contact-section .col-md-6{\r\n");
      out.write("  width: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-line{\r\n");
      out.write("  border-right: 1px solid #B29999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group{\r\n");
      out.write("  margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("label{\r\n");
      out.write("  font-size: 1.3em;\r\n");
      out.write("  line-height: 1em;\r\n");
      out.write("  font-weight: normal;\r\n");
      out.write("}\r\n");
      out.write(".form-control{\r\n");
      out.write("  font-size: 1.3em;\r\n");
      out.write("  color: #080808;\r\n");
      out.write("}\r\n");
      out.write("textarea.form-control {\r\n");
      out.write("    height: 135px;\r\n");
      out.write("   /* margin-top: px;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submit{\r\n");
      out.write("  font-size: 1.1em;\r\n");
      out.write("  float: right;\r\n");
      out.write("  width: 150px;\r\n");
      out.write("  background-color: transparent;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/contact\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<section id=\"contact\">\r\n");
      out.write("\t\t\t<div class=\"section-content\">\r\n");
      out.write("\t\t\t\t<h2 class=\"bg-primary\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("\t\t\t\t<h1 class=\"section-header\">Get in <span class=\"content-header wow fadeIn \" data-wow-delay=\"0.2s\" data-wow-duration=\"2s\"> Touch with us</span></h1>\r\n");
      out.write("\t\t\t\t<h3>Lorem Ipsum is simply dummy text of the printing and typesetting industry</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"contact-section\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 form-line\">\r\n");
      out.write("\t\t\t  \t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t  \t\t\t\t<label for=\"exampleInputUsername\">Your name</label>\r\n");
      out.write("\t\t\t\t\t    \t<input type=\"text\" name=\"name\" class=\"form-control\" id=\"\" placeholder=\" Enter Name\">\r\n");
      out.write("\t\t\t\t  \t\t</div>\r\n");
      out.write("\t\t\t\t  \t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t    \t<label for=\"exampleInputEmail\">Email Address</label>\r\n");
      out.write("\t\t\t\t\t    \t<input type=\"email\" name=\"email\" class=\"form-control\" id=\"exampleInputEmail\" placeholder=\" Enter Email id\">\r\n");
      out.write("\t\t\t\t\t  \t</div>\t\r\n");
      out.write("\t\t\t\t\t  \t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t    \t<label for=\"telephone\">Mobile No.</label>\r\n");
      out.write("\t\t\t\t\t    \t<input type=\"tel\" name=\"number\" class=\"form-control\" id=\"telephone\" placeholder=\" Enter 10-digit mobile no.\">\r\n");
      out.write("\t\t\t  \t\t\t</div>\r\n");
      out.write("\t\t\t  \t\t</div>\r\n");
      out.write("\t\t\t  \t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t  \t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t  \t\t\t\t<label for =\"description\"> Message</label>\r\n");
      out.write("\t\t\t  \t\t\t \t<textarea  class=\"form-control\" name=\"messageText\" id=\"description\" placeholder=\"Enter Your Message\"></textarea>\r\n");
      out.write("\t\t\t  \t\t\t</div>\r\n");
      out.write("\t\t\t  \t\t\t<div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t  \t\t\t\t<button type=\"submit\" class=\"btn btn-default submit\"><i class=\"fa fa-paper-plane\" aria-hidden=\"true\"></i>  Send Message</button>\r\n");
      out.write("\t\t\t  \t\t\t</div>\r\n");
      out.write("\t\t\t  \t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
